# Generated by Django 6.0.3 on 2026-04-08 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=50)),
                ('middle_name', models.CharField(blank=True, db_column='middle_name', max_length=50)),
                ('last_name', models.CharField(db_column='last_name', max_length=50)),
                ('email_address', models.EmailField(db_column='email_address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(db_column='is_locked', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decree_number', models.CharField(db_column='decree_number', max_length=50, unique=True)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('effect_type', models.CharField(choices=[('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('warning', 'Warning'), ('commendation', 'Commendation'), ('other', 'Other')], db_column='effect_type', max_length=50)),
                ('start_validity', models.DateField(db_column='start_validity')),
                ('end_validity', models.DateField(db_column='end_validity')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_column='department_name', max_length=100)),
                ('faculty_name', models.CharField(db_column='faculty_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('start_date', models.DateField(db_column='start_date')),
                ('defense_date', models.DateField(blank=True, db_column='defense_date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('defended', 'Defended'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='status', default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academic_rank', models.CharField(choices=[('assistant', 'Assistant Professor'), ('associate', 'Associate Professor'), ('full', 'Full Professor'), ('lecturer', 'Lecturer')], db_column='academic_rank', max_length=50)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university_id', models.CharField(db_column='university_id', max_length=20, unique=True)),
                ('enrollment_year', models.IntegerField(db_column='enrollment_year')),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], db_column='student_status', default='active', max_length=20)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_column='course_code', max_length=10, unique=True)),
                ('course_name', models.CharField(db_column='course_name', max_length=100)),
                ('credits', models.PositiveIntegerField(db_column='credits', default=3)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department')),
                ('professor', models.ForeignKey(db_column='professor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_column='semester', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True, db_column='enrollment_date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed'), ('failed', 'Failed')], db_column='status', default='active', max_length=20)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_column='semester', max_length=20)),
                ('exam_date', models.DateField(db_column='exam_date')),
                ('duration', models.IntegerField(db_column='duration')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamHallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(db_column='hall_name', max_length=50)),
                ('capacity', models.PositiveIntegerField(db_column='capacity')),
                ('exam_session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='core.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_mark', models.FloatField(db_column='practical_mark')),
                ('theoretical_mark', models.FloatField(db_column='theoretical_mark')),
                ('is_validated', models.BooleanField(db_column='is_validated', default=False)),
                ('is_locked', models.BooleanField(db_column='is_locked', default=False)),
                ('enrollment', models.OneToOneField(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='core.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_date', models.DateField(db_column='seminar_date')),
                ('report_summary', models.TextField(db_column='report_summary')),
                ('attendance_status', models.BooleanField(db_column='attendance_status', default=False)),
                ('thesis', models.ForeignKey(db_column='thesis_id', on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to='core.thesis')),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_theses', to='core.professor'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='core.student'),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('transcript', 'Transcript'), ('enrollment_certificate', 'Enrollment Certificate'), ('graduation_certificate', 'Graduation Certificate'), ('other', 'Other')], db_column='request_type', max_length=50)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected')], db_column='request_status', default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_column='request_date')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserDecree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, db_column='assignment_date')),
                ('decree', models.ForeignKey(db_column='decree_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_decrees', to='core.decree')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='decrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'decree')},
            },
        ),
    ]
