# Generated by Django 6.0.3 on 2026-03-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(db_column='firstName', max_length=50)),
                ('middleName', models.CharField(blank=True, db_column='middleName', max_length=50)),
                ('lastName', models.CharField(db_column='lastName', max_length=50)),
                ('emailAddress', models.EmailField(db_column='emailAddress', max_length=254, unique=True)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('isLocked', models.BooleanField(db_column='isLocked', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreeNumber', models.CharField(db_column='decreeNumber', max_length=50)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('effectType', models.CharField(db_column='effectType', max_length=50)),
                ('startValidity', models.DateField(db_column='startValidity')),
                ('endValidity', models.DateField(db_column='endValidity')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(db_column='departmentName', max_length=100)),
                ('facultyName', models.CharField(db_column='facultyName', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionCode', models.CharField(db_column='permissionCode', max_length=50)),
                ('permissionDescription', models.CharField(db_column='permissionDescription', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(db_column='roleName', max_length=50)),
                ('roleDescription', models.TextField(blank=True, db_column='roleDescription', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('startDate', models.DateField(db_column='startDate')),
                ('defenseDate', models.DateField(blank=True, db_column='defenseDate', null=True)),
                ('status', models.CharField(db_column='status', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academicRank', models.CharField(db_column='academicRank', max_length=50)),
                ('department', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('universityId', models.CharField(db_column='universityId', max_length=20, unique=True)),
                ('enrollmentYear', models.IntegerField(db_column='enrollmentYear')),
                ('studentStatus', models.CharField(db_column='studentStatus', max_length=20)),
                ('department', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(db_column='courseCode', max_length=10)),
                ('courseName', models.CharField(db_column='courseName', max_length=100)),
                ('department', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('professor', models.ForeignKey(db_column='professorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
        ),
        migrations.AddField(
            model_name='globaluser',
            name='department',
            field=models.ForeignKey(db_column='departmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_column='semester', max_length=20)),
                ('examDate', models.DateField(db_column='examDate')),
                ('duration', models.IntegerField(db_column='duration')),
                ('course', models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamHallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(db_column='hallName', max_length=50)),
                ('capacity', models.IntegerField(blank=True, db_column='capacity', null=True)),
                ('examSession', models.ForeignKey(db_column='sessionID', on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='core.examsession')),
            ],
        ),
        migrations.AddField(
            model_name='globaluser',
            name='role',
            field=models.ForeignKey(db_column='roleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permissionID', on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('role', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminarDate', models.DateField(db_column='seminarDate')),
                ('reportSummary', models.TextField(db_column='reportSummary')),
                ('attendanceStatus', models.BooleanField(db_column='attendanceStatus', default=False)),
                ('thesis', models.ForeignKey(db_column='thesisID', on_delete=django.db.models.deletion.CASCADE, to='core.thesis')),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(db_column='supervisorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalMark', models.FloatField(db_column='practicalMark')),
                ('theoreticalMark', models.FloatField(db_column='theoreticalMark')),
                ('isValidated', models.BooleanField(db_column='isValidated', default=False)),
                ('isLocked', models.BooleanField(db_column='isLocked', default=False)),
                ('course', models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(db_column='requestType', max_length=50)),
                ('requestStatus', models.CharField(db_column='requestStatus', default='Pending', max_length=20)),
                ('requestDate', models.DateTimeField(auto_now_add=True, db_column='requestDate')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserDecree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentDate', models.DateTimeField(auto_now_add=True, db_column='assignmentDate')),
                ('decree', models.ForeignKey(db_column='decreeID', on_delete=django.db.models.deletion.CASCADE, to='core.decree')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Decree',
                'unique_together': {('user', 'decree')},
            },
        ),
    ]
